project:
  type: book
  output-dir: _book

book:
  title: "Florida AFS 2023 Open Science Workshop"
  repo-url: https://github.com/tbep-tech/flafs-os-workshop
  date: last-modified
  reader-mode: true
  downloads: pdf
  page-footer:
    left: |
      Website created by Marcus Beck, with attribution to external content
    right: |
      This book was built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - part: "Modules"
      chapters:
        - basics.qmd
        - collaborate.qmd
        - impact.qmd
    - part: "Additional content"
      chapters:
        - implement.qmd
        - setup.qmd
        - rintro.qmd
        - resources.qmd
        - references.qmd
        - codeofconduct.qmd

bibliography: refs.bib

format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: 
      source: repo
  pdf:
    documentclass: scrreprt

execute: 
  echo: false
  warning: false
